env:
  es6: true
  node: true
  mocha: true

extends: "airbnb-base"

globals:
  assert: true
  browser: true
  expect: true

parserOptions:
  ecmaVersion: 6

root: true

rules:
  comma-dangle:
    - "error"
    - arrays: "always-multiline"
      objects: "always-multiline"
      imports: "never"
      exports: "never"
      functions: "ignore"
  global-require: "off"
  import/no-extraneous-dependencies: 0
  indent:
    - "error"
    - 4
    - SwitchCase: 1
  max-len:
    - "error"
    - 220
    - ignorePattern: '\s*\/\^(.*)\$\/,$'
  new-cap:
    - "error"
    - newIsCap: true
      capIsNewExceptions:
        - "Given"
        - "When"
        - "Then"
  strict: "off"
  valid-jsdoc:
    - "error"
    - requireReturn: false
      matchDescription: ".+"
  class-methods-use-this: "off"
  no-undef: "off"
  no-control-regex: "off"
  import/order: "off"
  no-unused-expressions: "off"
